services:
  postgres:
    image: postgres:latest
    container_name: lights-shop-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - lights-shop-network

  product-service:
    build:
      context: ./apps/backend/product-service
      dockerfile: Dockerfile
    container_name: lights-shop-product-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PRODUCT_SERVICE_PORT}
      NODE_ENV: development
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    depends_on:
      - postgres
    volumes:
      - ./apps/backend/product-service:/app
      - /app/node_modules
    networks:
      - lights-shop-network

  order-service:
    build:
      context: ./apps/backend/order-service
      dockerfile: Dockerfile
    container_name: lights-shop-order-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${ORDER_SERVICE_PORT}
      NODE_ENV: development
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    depends_on:
      - postgres
      - product-service
    volumes:
      - ./apps/backend/order-service:/app
      - /app/node_modules
    networks:
      - lights-shop-network

volumes:
  postgres-data:

networks:
  lights-shop-network:
    driver: bridge
